import { Inter } from "next/font/google";
import { ReduxProvider } from "../../redux/provider";
import NavbarDoc from "../../../../components/NavbarDoc";
import FooterDoc from "../../../../components/FooterDoc";

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`global-text ${inter.className}`}> 
        <NavbarDoc/>
        <ReduxProvider> {children} </ReduxProvider>
        <FooterDoc/>
      </body>
    </html>
  )
}
