export const DOCTOR_REQUEST = 'DOCTOR_REQUEST';
export const DOCTOR_SUCCESS = 'DOCTOR_SUCCESS';
export const DOCTOR_FAIL = 'DOCTOR_FAIL';
export const DOCTORS_VIEW_SUCCESS = 'DOCTORS_VIEW_SUCCESS';
export const DOCTORS_VIEW_REQUEST = 'DOCTORS_VIEW_REQUEST';
export const DOCTORS_VIEW_FAIL = 'DOCTORS_VIEW_FAIL';

export const DOCTORS_UPDATE_SUCCESS = 'DOCTORS_UPDATE_SUCCESS';
export const DOCTORS_UPDATE_REQUEST = 'DOCTORS_UPDATE_REQUEST';
export const DOCTORS_UPDATE_FAIL = 'DOCTORS_UPDATE_FAIL';

export const DOCTORS_VIEWPATIENTSINFO_SUCCESS = 'DOCTORS_VIEWPATIENTSINFO_SUCCESS';
export const DOCTORS_VIEWPATIENTSINFO_REQUEST = 'DOCTORS_VIEWPATIENTSINFO_REQUEST';
export const DOCTORS_VIEWPATIENTSINFO_FAIL = 'DOCTORS_VIEWPATIENTSINFO_FAIL';


export const DOCTORS_FILTERAPPOINTMENTS_SUCCESS = 'DOCTORS_FILTERAPPOINTMENTS_SUCCESS';
export const DOCTORS_FILTERAPPOINTMENTS_REQUEST = 'DOCTORS_FILTERAPPOINTMENTS_REQUEST';
export const DOCTORS_FILTERAPPOINTMENTS_FAIL = 'DOCTORS_FILTERAPPOINTMENTS_FAIL';
