export const DOCTOR_REQUEST = 'DOCTOR_REQUEST';
export const DOCTOR_SUCCESS = 'DOCTOR_SUCCESS';
export const DOCTOR_FAIL = 'DOCTOR_FAIL';
export const DOCTORS_VIEW_SUCCESS = 'DOCTORS_VIEW_SUCCESS';
export const DOCTORS_VIEW_REQUEST = 'DOCTORS_VIEW_REQUEST';
export const DOCTORS_VIEW_FAIL = 'DOCTORS_VIEW_FAIL';

export const DOCTORS_UPDATE_SUCCESS = 'DOCTORS_UPDATE_SUCCESS';
export const DOCTORS_UPDATE_REQUEST = 'DOCTORS_UPDATE_REQUEST';
export const DOCTORS_UPDATE_FAIL = 'DOCTORS_UPDATE_FAIL';

export const DOCTORS_VIEWPATIENTSINFO_SUCCESS = 'DOCTORS_VIEWPATIENTSINFO_SUCCESS';
export const DOCTORS_VIEWPATIENTSINFO_REQUEST = 'DOCTORS_VIEWPATIENTSINFO_REQUEST';
export const DOCTORS_VIEWPATIENTSINFO_FAIL = 'DOCTORS_VIEWPATIENTSINFO_FAIL';


export const DOCTORS_FILTERAPPOINTMENTS_SUCCESS = 'DOCTORS_FILTERAPPOINTMENTS_SUCCESS';
export const DOCTORS_FILTERAPPOINTMENTS_REQUEST = 'DOCTORS_FILTERAPPOINTMENTS_REQUEST';
export const DOCTORS_FILTERAPPOINTMENTS_FAIL = 'DOCTORS_FILTERAPPOINTMENTS_FAIL';


export const DOCTOR_ACCEPTED_SUCCESS = 'DOCTOR_ACCEPTED_SUCCESS';
export const DOCTOR_ACCEPTED_REQUEST = 'DOCTOR_ACCEPTED_REQUEST';
export const DOCTOR_ACCEPTED_FAIL = 'DOCTOR_ACCEPTED_FAIL';


export const DOCTOR_VIEWCONTRACT_REQUEST='DOCTOR_VIEWCONTRACT_REQUEST';
export const DOCTOR_VIEWCONTRACT_SUCCESS='DOCTOR_VIEWCONTRACT_SUCCESS';
export const DOCTOR_VIEWCONTRACT_FAIL='DOCTOR_VIEWCONTRACT_FAIL';


export const DOCTOR_ACCEPTCONTRACT_REQUEST='DOCTOR_ACCEPTCONTRACT_REQUEST';
export const DOCTOR_ACCEPTCONTRACT_SUCCESS='DOCTOR_ACCEPTCONTRACT_SUCCESS';
export const DOCTOR_ACCEPTCONTRACT_FAIL='DOCTOR_ACCEPTCONTRACT_FAIL';

export const DOCTOR_ADDAVAILABLEDATE_REQUEST='DOCTOR_ADDAVAILABLEDATE_REQUEST';
export const DOCTOR_ADDAVAILABLEDATE_SUCCESS='DOCTOR_ADDAVAILABLEDATE_SUCCESS';
export const DOCTOR_ADDAVAILABLEDATE_FAIL='DOCTOR_ADDAVAILABLEDATE_FAIL';


export const DOCTOR_FOLLOWUP_REQUEST='DOCTOR_FOLLOWUP_REQUEST';
export const DOCTOR_FOLLOWUP_SUCCESS='DOCTOR_FOLLOWUP_SUCCESS';
export const DOCTOR_FOLLOWUP_FAIL='DOCTOR_FOLLOWUP_FAIL';


export const DOCTOR_REJECTED_REQUEST='DOCTOR_REJECTED_REQUEST';
export const DOCTOR_REJECTED_SUCCESS='DOCTOR_REJECTED_SUCCESS';
export const DOCTOR_REJECTED_FAIL='DOCTOR_REJECTED_FAIL';

export const DOCTOR_DOWNLOAD_DOCS_REQUEST='DOCTOR_DOWNLOAD_DOCS_REQUEST';
export const DOCTOR_DOWNLOAD_DOCS_SUCCESS='DOCTOR_DOWNLOAD_DOCS_SUCCESS';
export const DOCTOR_DOWNLOAD_DOCS_FAIL='DOCTOR_DOWNLOAD_DOCS_FAIL';
