export const FAMILY_MEMBERS_REQUEST = 'FAMILY_MEMBERS_REQUEST';
export const FAMILY_MEMBERS_SUCCESS = 'FAMILY_MEMBERS_SUCCESS';
export const FAMILY_MEMBERS_FAIL = 'FAMILY_MEMBERS_FAIL';
export const VIEW_FAMILY_MEMBERS_REQUEST = 'VIEW_FAMILY_MEMBERS_REQUEST';
export const VIEW_FAMILY_MEMBERS_SUCCESS = 'VIEW_FAMILY_MEMBERS_REQUEST';
export const VIEW_FAMILY_MEMBERS_FAIL = 'VIEW_FAMILY_MEMBERS_FAIL';

