export const HEALTH_PACKAGES_LIST_REQUEST = 'HEALTH_PACKAGES_LIST_REQUEST';
export const HEALTH_PACKAGES_LIST_SUCCESS = 'HEALTH_PACKAGES_LIST_SUCCESS';
export const HEALTH_PACKAGES_LIST_FAIL = 'HEALTH_PACKAGES_LIST_FAIL';

export const HEALTH_PACKAGE_DETAILS_REQUEST = 'HEALTH_PACKAGE_DETAILS_REQUEST';
export const HEALTH_PACKAGE_DETAILS_SUCCESS = 'HEALTH_PACKAGE_DETAILS_SUCCESS';
export const HEALTH_PACKAGE_DETAILS_FAIL = 'HEALTH_PACKAGE_DETAILS_FAIL';

export const HEALTH_PACKAGE_DELETE_REQUEST = 'HEALTH_PACKAGE_DELETE_REQUEST';
export const HEALTH_PACKAGE_DELETE_SUCCESS = 'HEALTH_PACKAGE_DELETE_SUCCESS';
export const HEALTH_PACKAGE_DELETE_FAIL = 'HEALTH_PACKAGE_DELETE_FAIL';

export const HEALTH_PACKAGE_CREATE_REQUEST = 'HEALTH_PACKAGE_CREATE_REQUEST';
export const HEALTH_PACKAGE_CREATE_SUCCESS = 'HEALTH_PACKAGE_CREATE_SUCCESS';
export const HEALTH_PACKAGE_CREATE_FAIL = 'HEALTH_PACKAGE_CREATE_FAIL';

export const HEALTH_PACKAGE_UPDATE_REQUEST = 'HEALTH_PACKAGE_UPDATE_REQUEST';
export const HEALTH_PACKAGE_UPDATE_SUCCESS = 'HEALTH_PACKAGE_UPDATE_SUCCESS';
export const HEALTH_PACKAGE_UPDATE_FAIL = 'HEALTH_PACKAGE_UPDATE_FAIL';
