export const PATIENTS_REQUEST = "PATIENTS_REQUEST";
export const PATIENTS_SUCCESS = "PATIENTS_SUCCESS";
export const PATIENTS_FAIL = "PATIENTS_FAIL";
export const FILTER_PATIENTS_REQUEST = "PATIENTS_REQUEST";
export const FILTER_PATIENTS_SUCCESS = "PATIENTS_SUCCESS";
export const FILTER_PATIENTS_FAIL = "PATIENTS_FAIL";
