export const PATIENTS_FILTERAPPOINTMENTS_SUCCESS = 'PATIENTS_FILTERAPPOINTMENTS_SUCCESS';
export const PATIENTS_FILTERAPPOINTMENTS_REQUEST = 'PATIENTS_FILTERAPPOINTMENTS_REQUEST';
export const PATIENTS_FILTERAPPOINTMENTS_FAIL = 'PATIENTS_FILTERAPPOINTMENTS_FAIL';


export const PATIENT_SUCCESS = 'PATIENT_SUCCESS';
export const PATIENT_REQUEST = 'PATIENT_REQUEST';
export const PATIENT_FAIL = 'PATIENT_FAIL';

export const PATIENT_UPLOAD_DOCS_REQUEST = 'PATIENT_UPLOAD_DOCS_REQUEST';
export const PATIENT_UPLOAD_DOCS_SUCCESS = 'PATIENT_UPLOAD_DOCS_SUCCESS';
export const PATIENT_UPLOAD_DOCS_FAIL = 'PATIENT_UPLOAD_DOCS_FAIL';

export const PATIENT_DOWNLOAD_DOCS_REQUEST='PATIENT_DOWNLOAD_DOCS_REQUEST';
export const PATIENT_DOWNLOAD_DOCS_SUCCESS='PATIENT_DOWNLOAD_DOCS_SUCCESS';
export const PATIENT_DOWNLOAD_DOCS_FAIL='PATIENT_DOWNLOAD_DOCS_FAIL';


export const PATIENT_REMOVE_RECORD_REQUEST = 'PATIENT_REMOVE_RECORD_REQUEST';
export const PATIENT_REMOVE_RECORD_SUCCESS = 'PATIENT_REMOVE_RECORD_SUCCESS';
export const PATIENT_REMOVE_RECORD_FAIL = 'PATIENT_REMOVE_RECORD_FAIL';


export const PATIENT_UPLOAD_HEALTHRECORDS_REQUEST = 'PATIENT_UPLOAD_HEALTHRECORDS_REQUEST';
export const PATIENT_UPLOAD_HEALTHRECORDS_SUCCESS = 'PATIENT_UPLOAD_HEALTHRECORDS_SUCCESS';
export const PATIENT_UPLOAD_HEALTHRECORDS_FAIL = 'PATIENT_UPLOAD_HEALTHRECORDS_FAIL';

