export const PATIENTS_FILTERAPPOINTMENTS_SUCCESS = 'PATIENTS_FILTERAPPOINTMENTS_SUCCESS';
export const PATIENTS_FILTERAPPOINTMENTS_REQUEST = 'PATIENTS_FILTERAPPOINTMENTS_REQUEST';
export const PATIENTS_FILTERAPPOINTMENTS_FAIL = 'PATIENTS_FILTERAPPOINTMENTS_FAIL';
export const PATIENT_SUCCESS = 'PATIENT_SUCCESS';
export const PATIENT_REQUEST = 'PATIENT_REQUEST';
export const PATIENT_FAIL = 'PATIENT_FAIL';