export const PRESCRIPTIONS_REQUEST = 'PRESCRIPTIONS_REQUEST';
export const PRESCRIPTIONS_SUCCESS = 'PRESCRIPTIONS_SUCCESS';
export const PRESCRIPTIONS_FAIL = 'PRESCRIPTIONS_FAIL';
export const VIEW_PRESCRIPTIONS_REQUEST = 'PRESCRIPTIONS_REQUEST';
export const VIEW_PRESCRIPTIONS_SUCCESS = 'PRESCRIPTIONS_SUCCESS';
export const VIEW_PRESCRIPTIONS_FAIL = 'PRESCRIPTIONS_FAIL';

