import { Inter } from "next/font/google";
import { ReduxProvider } from "../redux/provider";
import NavbarPatient from "../../../components/NavbarPatient";
import Footer from "../../../components/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
      <div className={`global-text ${inter.className}`}>
        <NavbarPatient />
        <div className="p-2 my-5 mx-4">
        <ReduxProvider> {children} </ReduxProvider>
        </div>
        <Footer/>
      </div>
  );
}
