export const FOLLOWUP_REQUEST='FOLLOWUP_REQUEST';
export const FOLLOWUP_SUCCESS='FOLLOWUP_SUCCESS';
export const FOLLOWUP_FAIL='FOLLOWUP_FAIL';

export const RESCHEDULE_REQUEST='RESCHEDULE_REQUEST';
export const RESCHEDULE_SUCCESS='RESCHEDULE_SUCCESS';
export const RESCHEDULE_FAIL='RESCHEDULE_FAIL';


export const CANCEL_REQUEST='CANCEL_REQUEST';
export const CANCEL_SUCCESS='CANCEL_SUCCESS';
export const CANCEL_FAIL='CANCEL_FAIL';