import { Inter } from "next/font/google";
import { ReduxProvider } from "../../redux/provider";
import Navbar from "../../../../components/Navbar";
import Footer from "../../../../components/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <div className={`global-text ${inter.className}`}>
      <Navbar/>
      <div className="p-2 m-3">
        <ReduxProvider> {children} </ReduxProvider>
      </div>
      <Footer/>
    </div>
  );
}
